# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mongoid_ext 0.9.0 ruby lib

Gem::Specification.new do |s|
  s.name = "mongoid_ext"
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["David A. Cuadrado"]
  s.date = "2015-06-13"
  s.description = "mongoid plugins"
  s.email = "krawek@gmail.com"
  s.executables = ["mongoid_console"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/mongoid_console",
    "lib/mongoid_ext.rb",
    "lib/mongoid_ext/criteria_ext.rb",
    "lib/mongoid_ext/document_ext.rb",
    "lib/mongoid_ext/encryptor.rb",
    "lib/mongoid_ext/file.rb",
    "lib/mongoid_ext/file_list.rb",
    "lib/mongoid_ext/file_server.rb",
    "lib/mongoid_ext/filter.rb",
    "lib/mongoid_ext/filter/parser.rb",
    "lib/mongoid_ext/filter/result_set.rb",
    "lib/mongoid_ext/js/filter.js",
    "lib/mongoid_ext/js/find_tags.js",
    "lib/mongoid_ext/js/tag_cloud.js",
    "lib/mongoid_ext/modifiers.rb",
    "lib/mongoid_ext/mongo_mapper.rb",
    "lib/mongoid_ext/paranoia.rb",
    "lib/mongoid_ext/patches.rb",
    "lib/mongoid_ext/random.rb",
    "lib/mongoid_ext/slugizer.rb",
    "lib/mongoid_ext/storage.rb",
    "lib/mongoid_ext/tags.rb",
    "lib/mongoid_ext/types/embedded_hash.rb",
    "lib/mongoid_ext/types/open_struct.rb",
    "lib/mongoid_ext/types/timestamp.rb",
    "lib/mongoid_ext/types/translation.rb",
    "lib/mongoid_ext/update.rb",
    "lib/mongoid_ext/versioning.rb",
    "lib/mongoid_ext/voteable.rb",
    "mongoid_ext.gemspec",
    "test/helper.rb",
    "test/models.rb",
    "test/mongoid.yml",
    "test/mongoid4.yml",
    "test/test_encryptor.rb",
    "test/test_filter.rb",
    "test/test_modifiers.rb",
    "test/test_paranoia.rb",
    "test/test_random.rb",
    "test/test_slugizer.rb",
    "test/test_storage.rb",
    "test/test_tags.rb",
    "test/test_update.rb",
    "test/test_versioning.rb",
    "test/test_voteable.rb",
    "test/types/test_open_struct.rb",
    "test/types/test_set.rb",
    "test/types/test_timestamp.rb"
  ]
  s.homepage = "http://github.com/dcu/mongoid_ext"
  s.rubygems_version = "2.4.6"
  s.summary = "mongoid plugins"

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('mongoid', [">= 0"])
      s.add_runtime_dependency('uuidtools', [">= 2.1.1"])
      s.add_runtime_dependency('i18n', [">= 0"])
      s.add_runtime_dependency('tzinfo', [">= 0"])
      s.add_runtime_dependency('differ', [">= 0.1.2"])
      s.add_runtime_dependency('encryptor', ["~> 1.3.0"])
      s.add_runtime_dependency('rack', [">= 0"])
      s.add_development_dependency('minitest', [">= 0"])
      s.add_development_dependency('yard', ["~> 0.7"])
      s.add_development_dependency('rdoc', ["~> 3.12"])
      s.add_development_dependency('bundler', ["~> 1.0"])
      s.add_development_dependency('jeweler', ["~> 2.0.1"])
      s.add_development_dependency('simplecov', [">= 0"])
      s.add_development_dependency('timecop', [">= 0"])
      s.add_development_dependency('pry', [">= 0"])
    else
      s.add_dependency('mongoid', [">= 0"])
      s.add_dependency('uuidtools', [">= 2.1.1"])
      s.add_dependency('i18n', [">= 0"])
      s.add_dependency('tzinfo', [">= 0"])
      s.add_dependency('differ', [">= 0.1.2"])
      s.add_dependency('encryptor', ["~> 1.3.0"])
      s.add_dependency('rack', [">= 0"])
      s.add_dependency('minitest', [">= 0"])
      s.add_dependency('yard', ["~> 0.7"])
      s.add_dependency('rdoc', ["~> 3.12"])
      s.add_dependency('bundler', ["~> 1.0"])
      s.add_dependency('jeweler', ["~> 2.0.1"])
      s.add_dependency('simplecov', [">= 0"])
      s.add_dependency('timecop', [">= 0"])
      s.add_dependency('pry', [">= 0"])
    end
  else
    s.add_dependency('mongoid', [">= 0"])
    s.add_dependency('uuidtools', [">= 2.1.1"])
    s.add_dependency('i18n', [">= 0"])
    s.add_dependency('tzinfo', [">= 0"])
    s.add_dependency('differ', [">= 0.1.2"])
    s.add_dependency('encryptor', ["~> 1.3.0"])
    s.add_dependency('rack', [">= 0"])
    s.add_dependency('minitest', [">= 0"])
    s.add_dependency('yard', ["~> 0.7"])
    s.add_dependency('rdoc', ["~> 3.12"])
    s.add_dependency('bundler', ["~> 1.0"])
    s.add_dependency('jeweler', ["~> 2.0.1"])
    s.add_dependency('simplecov', [">= 0"])
    s.add_dependency('timecop', [">= 0"])
    s.add_dependency('pry', [">= 0"])
  end
end
